name: Integration Test

on:
  pull_request:
    branches: [main]


jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
 
      - name: Create Postgres Database and User
        run: |
          sudo -u postgres psql -c "CREATE USER ridham WITH PASSWORD 'password';" 2>/dev/null
          sudo -u postgres psql -c "CREATE DATABASE userdb" 2>/dev/null
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE userdb to ridham;" 2>/dev/null
 
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          DB_USER: ridham
          DB_PASSWORD: password
          DB_HOST: 127.0.0.1
          DB_NAME: userdb
          DB_PORT: 5432
          NODE_ENV: testing