name: Integration Test

on:
  pull_request:
    branches: [main]


jobs:
  connect-remote:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: ${{ secrets.DB_USERNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install Postgres
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

      - name: Postgres Database and User creation 
        run: |
          sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null
          sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;" 2>/dev/null
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME to $DB_USER;" 2>/dev/null
          sudo -u postgres psql -c "\l" 2>/dev/null

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432