name: Packer code Validation

on:
  pull_request:
    branches: [main]

jobs:
  check-packer-code:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"

      - name: Packer format
        run: packer fmt -check .
      
      - name: Packer validate
        run: packer validate .
 
        