name: Packer build

on:
  push:
    branches: [test-packer-actions]

jobs:
  integration-test-job:
    name: Integration Test Job
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: UserDB
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test
        env:
          DB_USER: "postgres"
          DB_PASSWORD: "postgres"
          DB_HOST: "127.0.0.1"
          DB_NAME: "UserDB"
          DB_PORT: 5432

  build-artifact-setup-gcloud:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: integration-test-job
    if: github.event.pull_request.merged == true  # Only run if the pull request is merged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info
      
      - name: Build Application Artifact
        run: |
          zip -r my-webapp-copy.zip .
      
      - name: Packer Init
        run: packer init ./packer/gcp-centos8.pkr.hcl

      - name: Packer Build
        run: |
          packer build -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'zone=${{ secrets.GCP_ZONE }}' -var 'app_code=my-webapp-copy.zip' ./packer/gcp-centos8.pkr.hcl
