name: Packer code Validation

on:
  pull_request:
    branches: [main]

jobs:
  check-packer-code:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.1"
      
      - name: Build Application Artifact
        run: |
          zip -r my-webapp-copy.zip .
      
      - name: Setup `packer` and install plugins
        run: |
          packer init ./packer/gcp-centos8.pkr.hcl
          packer init -upgrade

      - name: Packer format
        run: packer fmt -check ./packer/gcp-centos8.pkr.hcl
      
      - name: Packer validate
        run: |
          packer build -var 'project_id=${{ secrets.GCP_PROJECT_ID }}' -var 'zone=${{ secrets.GCP_ZONE }}' ./packer/gcp-centos8.pkr.hcl
 
        